name: Build and Deploy Cookbook
on: [push]
jobs:
  deploy:
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    env: 
      working-directory: ./cookbook-ghpage
    steps:
      - uses: actions/checkout@main
      
      - name: Directory List
        run: ls -R

      - name: Install
        run: npm install
      
      - name: Deploy
        uses: actions/deploy-pages@v2