name: Build and Deploy Cookbook
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Install
        run: npm install

      - name: Build Page
        run: npm run build

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2