name: Build and Deploy Cookbook
on: [push]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env: 
      working-directory: ./cookbook-ghpage
    steps:
      - run: npm run deploy -- -m "DEPLOYING"