name: Build and Deploy Cookbook
on: [push]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env: 
      working-directory: ./cookbook-ghpage
    steps:
      - uses: actions/checkout@main
      
      - name: Directory List
        run: ls -R

      - name: Install
        run: npm install

      - name: Git Configure
        run: |
          git config --global user.email "chriskmann32@gmail.com"
          git config --global user.name "chriskmann32"
      
      - name: Deploy
        run: npm run deploy -- -m "DEPLOYING"