name: Upload Recipe CSV
on:
  workflow_dispatch:
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: recipes
          path: ./src/csv/recipes.csv