name: Upload Recipe CSV
on:
  workflow_dispatch:
jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: recipes
          path: ./src/csv/recipes.csv